### ISSUE TITLE
Welcome pop-up on each macOS app launch

### ISSUE THREAD

**Issue by anijatsu** [mshibanami/redirect-web#21]
Every time I launch the application on macOS I get the welcome pop-up, suggesting that I enable the extension in Safari... but I have already done so.
Is this supposed to happen? I'd prefer to only get this pop-up if the app was newly installed.
Safari Version 17.4 (19618.1.13.11.5)
Redirect Web for Safari Version 5.1.1 (300000000204)
<img width="555" alt="Screenshot 2024-02-18 at 19 06 27" src="https://github.com/mshibanami/redirect-web/assets/1882015/eb78ae94-3651-4fb9-926d-8e4dff99ab27">

**Comment by mshibanami** [comment]
Hi @anijatsu. The screen you're seeing is likely because you haven't opened the extension pop-up in Safari. Currently, this extension determines whether you've completed the setup by checking if you've opened it at least once. Could you please take a look?

By the way, this might be a common issue for those who installed the iOS app first and then the macOS app. I'll reconsider this implementation. Thanks for your feedback.

**Comment by anijatsu** [comment]
> Currently, this extension determines whether you've completed the setup by checking if you've opened it at least once. Could you please take a look?
I have used the pop-up screen before, at least I think so - I sometimes used the add on icon next to the address bar in Safari to toggle a rule or the add on itself. 
> By the way, this might be a common issue for those who installed the iOS app first and then the macOS app. I'll reconsider this implementation. Thanks for your feedback.
That’s a likely root cause for me! I have first purchased and downloaded the app on iOS, and didn’t have the issue there.

**Comment by mshibanami** [comment]
I've released the new version which fixed this issue. I'm closing now. Thanks!
