### ISSUE TITLE
Redirect not working on scripts loaded by another script

### ISSUE THREAD

**Issue by ardunster** [mshibanami/redirect-web#24]
I'm attempting to use this extension to do local development work by redirecting the address our script gets hosted at to my localhost dev server.  The code runs inside a NextJS module federation so it needs the context of the entire website to work properly.  This works great in Chrome with the Redirector plugin, and I hoped that this would do the same thing in Safari, but it doesn't seem to even try to load from localhost, it just loads our deployed code with no errors. 

Addresses changed for privacy, but otherwise, here is the Redirector export json output: 

```
{
    "createdBy": "Redirector v3.5.3",
    "createdAt": "2024-04-09T18:04:30.486Z",
    "redirects": [
        {
            "description": "Localhost",
            "exampleUrl": "https://project.example.com/remoteEntry.js?cb=862.8932411336993",
            "exampleResult": "http://localhost:3030/remoteEntry.js?cb=862.8932411336993",
            "error": null,
            "includePattern": "https://project.example.com/*",
            "excludePattern": "",
            "patternDesc": "",
            "redirectUrl": "http://localhost:3030/$1",
            "patternType": "W",
            "processMatches": "noProcessing",
            "disabled": false,
            "grouped": false,
            "appliesTo": [
                "stylesheet",
                "script",
                "image",
                "xmlhttprequest"
            ]
        }
    ]
}
```

vs Redirect Web's export: 

```
{
  "appVersion" : "5.1.1",
  "bundleID" : "io.github.mshibanami.RedirectWebForSafari",
  "createdAt" : "2024-04-09T18:09:48.106Z",
  "kind" : "RedirectList",
  "redirects" : [
    {
      "captureGroupProcesses" : [

      ],
      "comments" : "",
      "destinationURLPattern" : "http:\/\/localhost:3030\/$1",
      "exampleURLs" : [
        "https:\/\/project.example.com\/remoteEntry.js?cb=862.8932411336993"
      ],
      "excludeURLPatterns" : [

      ],
      "isEnabled" : true,
      "kind" : "Redirect",
      "sourceURLPattern" : {
        "type" : "wildcard",
        "value" : "https:\/\/project.example.com\/*"
      },
      "title" : "Localhost"
    }
  ]
}
```

I don't see any options analogous to the "Applies to" field in Redirector. Is it even parsing requests made by one script to fetch another script?  The example URL and resulting modification look correct, but it just isn't working at all.

**Comment by mshibanami** [comment]
Hi @ardunster, this extension currently only supports redirection for a main window because Safari doesn't provide Web Extension API that Redirector uses in other browsers. (I guess that's why Redirector doesn't support Safari.)

On the other hand, Apple provides `declarativeNetRequest` API for this purpose, but Safari's implementation is broken: https://github.com/mshibanami/DeclarativeNetRequestIssue

I already sent Apple the bug report (FB13251357) last year, but there has been no response.

But I've been thinking of adopting this API anyway. I'm currently working on another feature, and once I release it, I will continue to work on that.

**Comment by ardunster** [comment]
Thanks for the answer.  For this purpose I ended up actually using a built in Safari Developer Tools feature, Local Overrides. If the extension gets updated to work like this in the future though it may be more convenient to pass around a config file!

**Comment by mshibanami** [comment]
Ah, Thanks for sharing it with me. That's great to know. 
Although your issue has been solved, yes, implementing this functionality would benefit many users. In fact, I have already received feature requests from a few users via email.

I will reopen this issue so that you and other users can track the progress.
Thanks!

**Comment by mshibanami** [comment]
Progress: In FB13232043, Apple replied to me that the related changes were submitted to Safari and WebKit. They will probably appear in the next release notes of Safari Technology Preview or something.

**Comment by mshibanami** [comment]
OK, I've released a new version 7 a few minutes ago, which includes support for the new DNR (Declarative Net Request) type.

@ardunster Would you mind taking another look if you have time? Thanks!

**Comment by ardunster** [comment]
I will try to remember to check it out at work next week!

**Comment by mshibanami** [comment]
I'm closing this issue now. Please feel free to reopen it if you encounter any problems.
