### ISSUE TITLE
redirect all URLs within a domain

### ISSUE THREAD

**Issue by 1bulf** [mshibanami/redirect-web#42]
Hello,

I have recently bought your app Redirect for Safari. I like the idea and the design of the app and the interface. I have found a shortcoming in your app. That is that when I open a specific link of the website, it does not redirect. It only redirects an URL like this (http://website.com/) but won`t redirect an URL like this (http://website.com/something/somethingelse). Please could you look into this? I think that adding an option whether to block other webpages in the domain would be good.

Best regards
Bulf

**Comment by mshibanami** [comment]
Hi @1bulf, sorry for any inconvenience.

What does your rule actually look like?

This could be caused by incorrect rule settings.
For example, this is a rule to redirect all URLs which start with https://example.com/:

![Screenshot 2024-07-19 at 9 42 25 PM](https://github.com/user-attachments/assets/4bbe23ef-8c76-45b4-8a26-f0990fa1e838)

Does it work for you?

Also, please make sure that you can open the sheet of the extension on Safari when you’re on the source website.

**Comment by 1bulf** [comment]
Hello, thank you very much. The issue is solved. I didn't know I have to manually add the asterisk into the URL from which the redirecting should happen. I had all my URLs without the asterisk.

**Comment by mshibanami** [comment]
That’s great!

For what it’s worth, I recently wrote a Getting Started page here: https://mshibanami.github.io/redirect-web/#/getting-started

That might help you find more different ways to create your rules. I hope you’ll enjoy it. :)
