### ISSUE TITLE
Option to not close the Safari tab

### ISSUE THREAD

**Issue by patrickrushton** [mshibanami/redirect-web#53]
I use a redirect rule to open YouTube pages in Video Lite. Often I will search for something in Safari and open a link from the Google results. If that link is a YouTube video then I can’t get back to the search results because Redirect has closed the Safari tab.

**Comment by mshibanami** [comment]
Hi @patrickrushton, I believe it's because you selected the corresponding option on the redirection screen here:

![Screenshot 2024-09-07 at 2 31 14 AM](https://github.com/user-attachments/assets/22e77c9f-371b-4b43-9525-4d3d25b40535)

You can disable it either on the screen above or on the following Edit screen:

![Screenshot 2024-09-07 at 2 33 19 AM](https://github.com/user-attachments/assets/3567baca-e2a3-4356-975c-2acfd7fa144e)

Whould you please take a look?

By the way, there is an issue that the navigation history is cleared when opening another app using Redirect Web. This is caused by Safari and it's tracked in this issue.: https://github.com/mshibanami/redirect-web/issues/52

**Comment by patrickrushton** [comment]
I don't seem to have a checkbox "Close the tab automatically" on iOS. I also don't have the "Application" select box. I'm just directing to a videolite:// url scheme.

**Comment by mshibanami** [comment]
@patrickrushton I see. Then it must be the same issue as #52.  
Yes, that option is only for macOS, and the tab you believe is closed is actually the same tab displaying a blank page bundled with the extension, which clears the history, making it seem like a new tab.

Currently, there is no workaround. Sorry for the inconvenience. However, as you can see in #52, Apple acknowledged this issue a week ago. So it could be fixed soon.

**Comment by patrickrushton** [comment]
Ah okay. Thanks for the explanation. Feel free to mark this one as a duplicate then.
