### ISSUE TITLE
Redirect to a selection of alternative websites

### ISSUE THREAD

**Issue by atutal** [mshibanami/redirect-web#61]
I would like to be able to redirect to a selection of websites. The use case concerns alternative privacy-friendly frontends to websites such as YouTube, Twitter, Reddit, Instagram. 

@Palumgarus has already created some redirect rules, which are limited to one redirect:
* https://github.com/mshibanami/redirect-web/discussions/29
* https://github.com/mshibanami/redirect-web/discussions/30
* https://github.com/mshibanami/redirect-web/discussions/26

Example:
`reddit.com → libreddit.privacydev.net$1 `

However, it often happens that an instance is not accessible. For this reason, there are many other instances of the same service. Currently, you have to change the instance manually if it is not accessible: 
`reddit.com → red.artemislena.eu$1`

Therefore, I would like to be able to redirect to a selection of websites: 
1. An automatically updated list of instances for many websites can be found here (also as json): https://github.com/libredirect/instances

2. In fact, there is already a paid extension for Safari that can do exactly this. Unfortunately, it has not been developed further for over a year and pull requests are not responded to: https://github.com/smmr-software/privacy-redirect-safari This is why I prefer this active project. 

<img src="https://github.com/user-attachments/assets/8ac3bb01-36e4-478a-9291-5b514708b59d" alt="example-alternative-redirect" width="450">

**Comment by mshibanami** [comment]
@atutal Thanks for your feedback!

I also recognize Palumgarus's posts. They're cool, but as you mentioned, the availability of the instances is an issue, which is one reason I didn't ask them for permission to include their rules in Redirect Web's library.

While I understand that some users use Redirect Web as an alternative to Privacy Redirect, I'm unsure how I should implement such a feature. In fact, it might not make sense to add that feature to Redirect Web, since it would involve checking the availability of the instances. Redirect Web is a general-purpose extension, so that doesn't seem very appropriate.

By the way, I just came up with a workaround: how about using a web page to check the availability of each instance and letting users jump to an available one? I experimentally created a page for redirecting Reddit to Redlib, here: https://mshibanami.github.io/redirect-web/misc/reddit-to-redlib.html

You can use this with this rule:

* Redirect From: `https://(www|new|old)\.reddit\.com/.*` (Regular Expression)
* Redirect To: `https://mshibanami.github.io/redirect-web/misc/reddit-to-redlib.html?url=$0`
* Capture Group Processing:
    * Group: `$0`
    * Process: `URL Encode`

![Screenshot 2024-10-21 at 6 15 19 PM](https://github.com/user-attachments/assets/a423b3b5-6cd6-4483-95b1-5b578adf130e)

Do you think this is what you're looking for? 🙂

**Comment by atutal** [comment]
Thank you @mshibanami for your quick and detailed response. I really like your idea of using a web page to check the availability of instances and redirect users to an available one—it’s a great and flexible way to handle the issue of instance availability.

I’ll definitely take a closer look at the code and the redirect rule. I also understand your point about Redirect Web being a general-purpose extension, and your solution aligns well with that vision. Thanks!

**Comment by mshibanami** [comment]
Glad to hear it also makes sense for your! Probably I'll dive deeper and put the related rules to the library later on. Thanks!

**Comment by atutal** [comment]
Thank you for that great solution @mshibanami and for mentioning me! I'd love to contribute if I have time.

I set up the jisk redirect rules on my Redirect-Web browser extension, and it works great! The reddit-to-redlib.html has functioned flawlessly over the past few months.

Keep up the fantastic work :)

**Comment by mshibanami** [comment]
Wow that's great to hear! Thanks for using it!
